version: "3"

services:
  db:
    platform: linux/amd64
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - backend
  
  app:
    image: 644435390668.dkr.ecr.us-east-1.amazonaws.com/lav:${IMAGE_VERSION}
    restart: always
    depends_on: 
      - db
    environment: 
      - ENV DB_DIALECT=MYSQL
      - ENV DB_URL=jdbc:mysql://db:3306/lavagna 
      - ENV DB_USER=root
      - ENV DB_PASS=12345
      - ENV SPRING_PROFILE=dev
    networks:
      - backend
      - frontend

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./src/main/webapp/setup/index.html:/usr/share/nginx/html/index.html
      - ./src/main/webapp/:/usr/share/nginx/html/static
    ports:
      - 80:80
    networks:
     - frontend
    depends_on:
      - app

volumes:
  mysql-data:

networks:
  backend:
  frontend: